### ISSUE TITLE
Implement efficiency and calculation

### ISSUE THREAD

**Issue by acampove** [HDembinski/jacobi#48]
Hello Hans,

Thank you for this project, we needed something like this for a long time and we had tried to implement it ourselves privately, but given our limited programming skills our implementations were far from what you have done.

However I have a suggestion. Many of us are trying to get away from ROOT, but there are things like:

https://root.cern.ch/doc/master/classTEfficiency.html

which are constantly needed to calculate efficiency errors. I wonder if Jacobi is a good place to add this feature. I do not see it implemented yet from what I saw in the documentation.

Cheers.

**Comment by HDembinski** [comment]
Hi, the TEfficiency functionality is implemented in Boost.Histogram and should be available in its Python wrapper boost-histogram. CC @henryiii
